version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
permissions:
  - object: /home/ubuntu/scripts
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu